// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0iAStVzylUKEPB5-RpzDe9IIvtLcHJ68',
    appId: '1:984574140514:web:715c7d9070f409d529b13b',
    messagingSenderId: '984574140514',
    projectId: 'flutter-firebase-dersler-13a91',
    authDomain: 'flutter-firebase-dersler-13a91.firebaseapp.com',
    storageBucket: 'flutter-firebase-dersler-13a91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU3eOSEumwryxdeTdViBJz96p53uJhBj4',
    appId: '1:984574140514:android:04e4505a46c1d8f529b13b',
    messagingSenderId: '984574140514',
    projectId: 'flutter-firebase-dersler-13a91',
    storageBucket: 'flutter-firebase-dersler-13a91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAevAoiBV3gASD9DqLBmB4-3EOtvQcvzLE',
    appId: '1:984574140514:ios:8643e139a51d3dba29b13b',
    messagingSenderId: '984574140514',
    projectId: 'flutter-firebase-dersler-13a91',
    storageBucket: 'flutter-firebase-dersler-13a91.appspot.com',
    iosBundleId: 'com.cahidenuryalcin.flutterFirebaseDersleri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAevAoiBV3gASD9DqLBmB4-3EOtvQcvzLE',
    appId: '1:984574140514:ios:8643e139a51d3dba29b13b',
    messagingSenderId: '984574140514',
    projectId: 'flutter-firebase-dersler-13a91',
    storageBucket: 'flutter-firebase-dersler-13a91.appspot.com',
    iosBundleId: 'com.cahidenuryalcin.flutterFirebaseDersleri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0iAStVzylUKEPB5-RpzDe9IIvtLcHJ68',
    appId: '1:984574140514:web:1e178cc9156ec89729b13b',
    messagingSenderId: '984574140514',
    projectId: 'flutter-firebase-dersler-13a91',
    authDomain: 'flutter-firebase-dersler-13a91.firebaseapp.com',
    storageBucket: 'flutter-firebase-dersler-13a91.appspot.com',
  );
}
